### ISSUE TITLE
Implementation of FlexTrak Transceiver Downlink for msp430

### ISSUE THREAD

**Issue by xszymonzur** [guorbit/obc-firmware#10]
The features for the OBC contained in [modelling PR #54](https://github.com/guorbit/obc-model/pull/54) shall be implemented in TASTE:

- [ ] add the serial communication library for msp430 (courtesy of @chgio)
- [ ] create a cmd queue, provide appropriate API
- [ ] send configuration to FlexTrack
- [ ] parse the FlexTrack UART messages

**Comment by chgio** [comment]
closing for abandonment of the FlexTrak in favour of an in-house-developed comms module based on the [STM32WL55JC Nucleo Devkit](https://www.st.com/en/evaluation-tools/nucleo-wl55jc.html).
thank you very much @xszymonzur for all your great work, keeping it for docs.
